from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS, WEB_DIRECTORY
from .audio_nodes import AUDIO_NODE_CLASS_MAPPINGS, AUDIO_NODE_DISPLAY_NAME_MAPPINGS
from .effect_nodes import EFFECT_NODE_CLASS_MAPPINGS, EFFECT_NODE_DISPLAY_NAME_MAPPINGS
from .filter_nodes import FILTER_NODE_CLASS_MAPPINGS, FILTER_NODE_DISPLAY_NAME_MAPPINGS
from .text_nodes import TEXT_NODE_CLASS_MAPPINGS, TEXT_NODE_DISPLAY_NAME_MAPPINGS
from .transition_nodes import TRANSITION_NODE_CLASS_MAPPINGS, TRANSITION_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS.update(AUDIO_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(EFFECT_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(FILTER_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TEXT_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TRANSITION_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS.update(AUDIO_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(EFFECT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FILTER_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TEXT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TRANSITION_NODE_DISPLAY_NAME_MAPPINGS)

# Use a package-unique ID so a node with the same generic name from another
# custom-node package cannot overwrite this node in ComfyUI's global registry.
NODE_CLASS_MAPPINGS["VideoSplitAudioConcat"] = AUDIO_NODE_CLASS_MAPPINGS["VideoSplitAudioConcat"]
NODE_DISPLAY_NAME_MAPPINGS["VideoSplitAudioConcat"] = "Audio Concat (Video Split)"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
